commands:
- orange-canvas
default_channels:
- defaults
default_environment: default
description: ''
dev_tool: false
environments:
  default: env.yaml
icon: icon.png
is_app: true
is_conda_app: true
is_default: false
name: orange-app
version: 0.1.0
