commands:
- open ${PREFIX}/bin/jupyter_mac.command
default_channels:
- defaults
default_environment: default
description: ''
dev_tool: true
environments:
  default: env.yaml
icon: icon.png
is_app: true
is_conda_app: true
is_default: false
name: notebook
version: 0.1.0
